export const videoMaps = {
    asl: {
      // Words
      'hello': "assets/asl/Hello.mp4",
      'age': "assets/asl/Age.mp4",
      'name': "assets/asl/Name.mp4",
      'again': "assets/asl/Again.mp4",
      'bad': "assets/asl/Bad.mp4",
      'busy': "assets/asl/Busy.mp4",
      'byebye': "assets/asl/ByeBye.mp4",
      'come':  "assets/asl/come.mp4",
      'deaf': "assets/asl/Deaf.mp4",
      "don't understand": "assets/asl/DontUnderstand.mp4",
      "fine": "assets/asl/Fine.mp4",
      "friend": "assets/asl/Friend.mp4",
      "go": "assets/asl/Go.mp4",
      "good": "assets/asl/good.mp4",
      "great": "assets/asl/Great.mp4",
      "have": "assets/asl/have.mp4",
      "hearing": "assets/asl/Hearing.mp4",
      "how are you": "assets/asl/HowAreYou.mp4",
      "learn": "assets/asl/learn.mp4",
      "like": "assets/asl/like.mp4",
      "no": "assets/asl/No.mp4",
      "nothing": "assets/asl/nothing.mp4",
      "not like": "assets/asl/NotLike.mp4",
      "oh i see": "assets/asl/OhISee.mp4",
      "please": "assets/asl/Please.mp4",
      "ready": "assets/asl/Ready.mp4",
      "repeat": "assets/asl/Repeat.mp4",
      "sign": "assets/asl/sign.mp4",
      "slow": "assets/asl/slow.mp4",
      "sorry": "assets/asl/Sorry.mp4",
      "thank you": "assets/asl/ThankYou.mp4",
      "understand": "assets/asl/Understand.mp4",
      "want": "assets/asl/want.mp4",
      "what": "assets/asl/What.mp4",
      "where": "assets/asl/where.mp4",
      "work": "assets/asl/Work.mp4",
      "yes": "assets/asl/Yes.mp4",


      // Numbers
      '0': 'assets/asl/0.mp4',
      '1': 'assets/asl/1.mp4',
      '2': 'assets/asl/2.mp4',
      '3': 'assets/asl/3.mp4',
      '4': 'assets/asl/4.mp4',
      '5': 'assets/asl/5.mp4',
      '6': 'assets/asl/6.mp4',
      '7': 'assets/asl/7.mp4',
      '8': 'assets/asl/8.mp4',
      '9': 'assets/asl/9.mp4',
      '10': 'assets/asl/10.mp4',


      // Alphabets
      'a': 'assets/asl/A.mp4',
      'b': 'assets/asl/B.mp4',
      'c': 'assets/asl/C.mp4',
      'd': 'assets/asl/D.mp4',
      'e': 'assets/asl/E.mp4',
      'f': 'assets/asl/F.mp4',
      'g': 'assets/asl/G.mp4',
      'h': 'assets/asl/H.mp4',
      'i': 'assets/asl/I.mp4',
      'j': 'assets/asl/J.mp4',
      'k': 'assets/asl/K.mp4',
      'l': 'assets/asl/L.mp4',
      'm': 'assets/asl/M.mp4',
      'n': 'assets/asl/N.mp4',
      'o': 'assets/asl/O.mp4',
      'p': 'assets/asl/P.mp4',
      'q': 'assets/asl/Q.mp4',
      'r': 'assets/asl/R.mp4',
      's': 'assets/asl/S.mp4',
      't': 'assets/asl/T.mp4',
      'u': 'assets/asl/U.mp4',
      'v': 'assets/asl/V.mp4',
      'w': 'assets/asl/W.mp4',
      'x': 'assets/asl/X.mp4',
      'y': 'assets/asl/Y.mp4',
      'z': 'assets/asl/Z.mp4'

    },
    isl: {

      // Words
      "again": "assets/isl/again.mp4",
      "alone": "assets/isl/alone.mp4",
      "and": "assets/isl/and.mp4",
      "bad": "assets/isl/bad.mp4",
      "boy": "assets/isl/boy.mp4",
      "bye": "assets/isl/bye.mp4",
      "child": "assets/isl/child.mp4",
      "correct": "assets/isl/correct.mp4",
      "day": "assets/isl/day.mp4",
      "easy": "assets/isl/easy.mp4",
      "food": "assets/isl/food.mp4",
      "girl": "assets/isl/girl.mp4",
      "good": "assets/isl/good.mp4",
      "good morning": "assets/isl/GoodMorning.mp4",
      "good night": "assets/isl/GoodNight.mp4",
      "he": "assets/isl/he.mp4",
      "hello": "assets/isl/hello.mp4",
      "man": "assets/isl/Man.mp4",
      "me": "assets/isl/me.mp4",
      "morning": "assets/isl/morning.mp4",
      "my name is": "assets/isl/MyNameIs.mp4",
      "namaste": "assets/isl/namaste.mp4",
      "no": "assets/isl/No.mp4",
      "please": "assets/isl/Please.mp4",
      "she": "assets/isl/she.mp4",
      "sorry": "assets/isl/Sorry.mp4",
      "strong": "assets/isl/strong.mp4",
      "thanks": "assets/isl/thanks.mp4",
      "thank you": "assets/isl/ThankYou.mp4",
      "thin": "assets/isl/thin.mp4",
      "understand": "assets/isl/understand.mp4",
      "weak": "assets/isl/weak.mp4",
      "welcome": "assets/isl/welcome.mp4",
      "woman": "assets/isl/Woman.mp4",
      "wrong": "assets/isl/wrong.mp4",
      "yes": "assets/isl/yes.mp4",


      // Numbers
      '0': 'assets/isl/0.mp4',
      '1': 'assets/isl/1.mp4',
      '2': 'assets/isl/2.mp4',
      '3': 'assets/isl/3.mp4',
      '4': 'assets/isl/4.mp4',
      '5': 'assets/isl/5.mp4',
      '6': 'assets/isl/6.mp4',
      '7': 'assets/isl/7.mp4',
      '8': 'assets/isl/8.mp4',
      '9': 'assets/isl/9.mp4',
      '10': 'assets/isl/10.mp4',


      // Alphabets
      'a': 'assets/isl/A.mp4',
      'b': 'assets/isl/B.mp4',
      'c': 'assets/isl/C.mp4',
      'd': 'assets/isl/D.mp4',
      'e': 'assets/isl/E.mp4',
      'f': 'assets/isl/F.mp4',
      'g': 'assets/isl/G.mp4',
      'h': 'assets/isl/H.mp4',
      'i': 'assets/isl/I.mp4',
      'j': 'assets/isl/J.mp4',
      'k': 'assets/isl/K.mp4',
      'l': 'assets/isl/L.mp4',
      'm': 'assets/isl/M.mp4',
      'n': 'assets/isl/N.mp4',
      'o': 'assets/isl/O.mp4',
      'p': 'assets/isl/P.mp4',
      'q': 'assets/isl/Q.mp4',
      'r': 'assets/isl/R.mp4',
      's': 'assets/isl/S.mp4',
      't': 'assets/isl/T.mp4',
      'u': 'assets/isl/U.mp4',
      'v': 'assets/isl/V.mp4',
      'w': 'assets/isl/W.mp4',
      'x': 'assets/isl/X.mp4',
      'y': 'assets/isl/Y.mp4',
      'z': 'assets/isl/Z.mp4',

    },
  };